apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: native-ingress-controller-system
resources:
- deployment.yaml
- rbac.yaml
- service.yaml
- webhook.yaml
- serviceaccount.yaml